name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Structurizr Site Generatr
        run: |
          VERSION=1.5.2
          wget https://github.com/avisi-cloud/structurizr-site-generatr/releases/download/${VERSION}/structurizr-site-generatr-${VERSION}.zip
          unzip structurizr-site-generatr-${VERSION}.zip
          chmod +x structurizr-site-generatr-${VERSION}/bin/structurizr-site-generatr
          echo "=== Checking structurizr-site-generatr version and options ==="
          ./structurizr-site-generatr-${VERSION}/bin/structurizr-site-generatr --help || true
          ./structurizr-site-generatr-${VERSION}/bin/structurizr-site-generatr version || true

      - name: Generate site
        run: |
          VERSION=1.5.2
          ./structurizr-site-generatr-${VERSION}/bin/structurizr-site-generatr generate-site --workspace-file diagram.dsl


      - name: Add .nojekyll file
        run: touch -p build/serve/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/serve
          publish_branch: gh-pages
